export const playlistCategories = [
  {
    category: "pop",
    title: "Pop",
    details: [
      {
        name: "Top Pop",
        id: 1,
        img: "https://i.scdn.co/image/ab67706f00000003b82f5272ca913b85b73f1690",
        description: "Bringing the pop.",
      },
      {
        name: "Pop Music",
        id: 2,
        img: "https://th.bing.com/th/id/OIP.X6Bv0OhuZCjTWHKbPABwjAHaHa?w=182&h=182&c=7&r=0&o=5&dpr=1.3&pid=1.7",
        description: "Pop hits.",
      },
      {
        name: "Pop",
        id: 3,
        img: "https://th.bing.com/th/id/OIP.2MzWXHRHaX6-sYliciRc1AAAAA?rs=1&pid=ImgDetMain",
        description: "Music, pop style.",
      },
      {
        name: "Now That's What I Call Pop",
        id: 4,
        img: "https://th.bing.com/th/id/OIP.5JL1V9hPFPddTh61XBd1ggHaGr?rs=1&pid=ImgDetMain",
        description: "Greatest pop hits.",
      },
    ],
  },
  {
    category: "rock",
    title: "Rock",
    details: [
      {
        name: "Rock",
        id: 5,
        img: "https://th.bing.com/th/id/OIP.FduqH2omwjTUl38Q6eqICAHaHa?w=192&h=191&c=7&r=0&o=5&dpr=1.3&pid=1.7",
        description: "Rock on.",
      },
      {
        name: "Rock Covers",
        id: 6,
        img: "https://th.bing.com/th/id/OIP.KiLvm9LGrSPFJub-z1-jAQAAAA?rs=1&pid=ImgDetMain",
        description: "Rock covers of the greatest hits.",
      },
      {
        name: "Rock 'n' Roll",
        id: 7,
        img: "https://i.pinimg.com/originals/36/97/ea/3697eaa4bfff0ce5360cee36bf14782c.jpg",
        description: "Keep on rocking!",
      },
      {
        name: "Rock Classics",
        id: 8,
        img: "https://th.bing.com/th/id/OIP.hy70mRt11OcdY8Y7kykDawHaHa?rs=1&pid=ImgDetMain",
        description: "When you need to re-live the classic hits.",
      },
    ],
  },
  {
    category: "hiphop",
    title: "Hip-Hop",
    details: [
      {
        name: "Playlist 1",
        id: 13,
        img: "https://th.bing.com/th/id/OIP.Nk61v0P3BKzP3P936XBRFAHaF2?w=237&h=188&c=7&r=0&o=5&dpr=1.3&pid=1.7",
        description: "this is the description",
      },
      {
        name: "Playlist 2",
        id: 14,
        img: "https://th.bing.com/th/id/OIP.Nk61v0P3BKzP3P936XBRFAHaF2?w=237&h=188&c=7&r=0&o=5&dpr=1.3&pid=1.7",
        description: "this is the description",
      },
      {
        name: "Playlist 3",
        id: 15,
        img: "https://th.bing.com/th/id/OIP.Nk61v0P3BKzP3P936XBRFAHaF2?w=237&h=188&c=7&r=0&o=5&dpr=1.3&pid=1.7",
        description: "this is the description",
      },
      {
        name: "Playlist 4",
        id: 16,
        img: "https://th.bing.com/th/id/OIP.Nk61v0P3BKzP3P936XBRFAHaF2?w=237&h=188&c=7&r=0&o=5&dpr=1.3&pid=1.7",
        description: "this is the description",
      },
      {
        name: "Playlist 5",
        id: 17,
        img: "https://th.bing.com/th/id/OIP.Nk61v0P3BKzP3P936XBRFAHaF2?w=237&h=188&c=7&r=0&o=5&dpr=1.3&pid=1.7",
        description: "this is the description",
      },
      {
        name: "Playlist 6",
        id: 18,
        img: "https://th.bing.com/th/id/OIP.Nk61v0P3BKzP3P936XBRFAHaF2?w=237&h=188&c=7&r=0&o=5&dpr=1.3&pid=1.7",
        description: "this is the description",
      },
    ],
  },
  {
    category: "mood",
    title: "Mood",
    details: [
      {
        name: "Playlist 1",
        id: 19,
        img: "https://th.bing.com/th/id/OIP.-XRNL7zQVO9-DVhs3V0f7QHaHa?w=161&h=180&c=7&r=0&o=5&dpr=1.3&pid=1.7",
        description: "this is the description",
      },
      {
        name: "Playlist 2",
        id: 20,
        img: "https://th.bing.com/th/id/OIP.-XRNL7zQVO9-DVhs3V0f7QHaHa?w=161&h=180&c=7&r=0&o=5&dpr=1.3&pid=1.7",
        description: "this is the description",
      },
      {
        name: "Playlist 3",
        id: 21,
        img: "https://th.bing.com/th/id/OIP.-XRNL7zQVO9-DVhs3V0f7QHaHa?w=161&h=180&c=7&r=0&o=5&dpr=1.3&pid=1.7",
        description: "this is the description",
      },
      {
        name: "Playlist 4",
        id: 22,
        img: "https://th.bing.com/th/id/OIP.-XRNL7zQVO9-DVhs3V0f7QHaHa?w=161&h=180&c=7&r=0&o=5&dpr=1.3&pid=1.7",
        description: "this is the description",
      },
      {
        name: "Playlist 5",
        id: 23,
        img: "https://th.bing.com/th/id/OIP.-XRNL7zQVO9-DVhs3V0f7QHaHa?w=161&h=180&c=7&r=0&o=5&dpr=1.3&pid=1.7",
        description: "this is the description",
      },
      {
        name: "Playlist 6",
        id: 24,
        img: "https://th.bing.com/th/id/OIP.-XRNL7zQVO9-DVhs3V0f7QHaHa?w=161&h=180&c=7&r=0&o=5&dpr=1.3&pid=1.7",
        description: "this is the description",
      },
    ],
  },
  {
    category: "party",
    title: "Party",
    details: [
      {
        name: "Playlist 1",
        id: 25,
        img: "https://th.bing.com/th?q=Best+DJ+Party+Music&w=120&h=120&c=1&rs=1&qlt=90&cb=1&dpr=1.3&pid=InlineBlock&mkt=ja-JP&cc=JP&setlang=en&adlt=moderate&t=1&mw=247",
        description: "this is the description",
      },
      {
        name: "Playlist 2",
        id: 26,
        img: "https://th.bing.com/th?q=Best+DJ+Party+Music&w=120&h=120&c=1&rs=1&qlt=90&cb=1&dpr=1.3&pid=InlineBlock&mkt=ja-JP&cc=JP&setlang=en&adlt=moderate&t=1&mw=247",
        description: "this is the description",
      },
      {
        name: "Playlist 3",
        id: 27,
        img: "https://th.bing.com/th?q=Best+DJ+Party+Music&w=120&h=120&c=1&rs=1&qlt=90&cb=1&dpr=1.3&pid=InlineBlock&mkt=ja-JP&cc=JP&setlang=en&adlt=moderate&t=1&mw=247",
        description: "this is the description",
      },
      {
        name: "Playlist 4",
        id: 28,
        img: "https://th.bing.com/th?q=Best+DJ+Party+Music&w=120&h=120&c=1&rs=1&qlt=90&cb=1&dpr=1.3&pid=InlineBlock&mkt=ja-JP&cc=JP&setlang=en&adlt=moderate&t=1&mw=247",
        description: "this is the description",
      },
      {
        name: "Playlist 5",
        id: 29,
        img: "https://th.bing.com/th?q=Best+DJ+Party+Music&w=120&h=120&c=1&rs=1&qlt=90&cb=1&dpr=1.3&pid=InlineBlock&mkt=ja-JP&cc=JP&setlang=en&adlt=moderate&t=1&mw=247",
        description: "this is the description",
      },
      {
        name: "Playlist 6",
        id: 30,
        img: "https://th.bing.com/th?q=Best+DJ+Party+Music&w=120&h=120&c=1&rs=1&qlt=90&cb=1&dpr=1.3&pid=InlineBlock&mkt=ja-JP&cc=JP&setlang=en&adlt=moderate&t=1&mw=247",
        description: "this is the description",
      },
    ],
  },
  {
    category: "kpop",
    title: "K-Pop",
    details: [
      {
        name: "Playlist 1",
        id: 31,
        img: "https://th.bing.com/th/id/OIP.YvjJgFrFcGMyVd6S2y2tBgHaHa?w=160&h=180&c=7&r=0&o=5&dpr=1.3&pid=1.7",
        description: "this is the description",
      },
      {
        name: "Playlist 2",
        id: 32,
        img: "https://th.bing.com/th/id/OIP.YvjJgFrFcGMyVd6S2y2tBgHaHa?w=160&h=180&c=7&r=0&o=5&dpr=1.3&pid=1.7",
        description: "this is the description",
      },
      {
        name: "Playlist 3",
        id: 33,
        img: "https://th.bing.com/th/id/OIP.YvjJgFrFcGMyVd6S2y2tBgHaHa?w=160&h=180&c=7&r=0&o=5&dpr=1.3&pid=1.7",
        description: "this is the description",
      },
      {
        name: "Playlist 4",
        id: 34,
        img: "https://th.bing.com/th/id/OIP.YvjJgFrFcGMyVd6S2y2tBgHaHa?w=160&h=180&c=7&r=0&o=5&dpr=1.3&pid=1.7",
        description: "this is the description",
      },
      {
        name: "Playlist 5",
        id: 35,
        img: "https://th.bing.com/th/id/OIP.YvjJgFrFcGMyVd6S2y2tBgHaHa?w=160&h=180&c=7&r=0&o=5&dpr=1.3&pid=1.7",
        description: "this is the description",
      },
      {
        name: "Playlist 6",
        id: 36,
        img: "https://th.bing.com/th/id/OIP.YvjJgFrFcGMyVd6S2y2tBgHaHa?w=160&h=180&c=7&r=0&o=5&dpr=1.3&pid=1.7",
        description: "this is the description",
      },
    ],
  },
  {
    category: "indie",
    title: "Indie",
    details: [
      {
        name: "Playlist 1",
        id: 37,
        img: "https://th.bing.com/th/id/OIP.4lfTxOQlytdkKhPZrCvDqgHaHa?w=200&h=200&c=7&r=0&o=5&dpr=1.3&pid=1.7",
        description: "this is the description",
      },
      {
        name: "Playlist 2",
        id: 38,
        img: "https://th.bing.com/th/id/OIP.4lfTxOQlytdkKhPZrCvDqgHaHa?w=200&h=200&c=7&r=0&o=5&dpr=1.3&pid=1.7",
        description: "this is the description",
      },
      {
        name: "Playlist 3",
        id: 39,
        img: "https://th.bing.com/th/id/OIP.4lfTxOQlytdkKhPZrCvDqgHaHa?w=200&h=200&c=7&r=0&o=5&dpr=1.3&pid=1.7",
        description: "this is the description",
      },
      {
        name: "Playlist 4",
        id: 40,
        img: "https://th.bing.com/th/id/OIP.4lfTxOQlytdkKhPZrCvDqgHaHa?w=200&h=200&c=7&r=0&o=5&dpr=1.3&pid=1.7",
        description: "this is the description",
      },
      {
        name: "Playlist 5",
        id: 41,
        img: "https://th.bing.com/th/id/OIP.4lfTxOQlytdkKhPZrCvDqgHaHa?w=200&h=200&c=7&r=0&o=5&dpr=1.3&pid=1.7",
        description: "this is the description",
      },
      {
        name: "Playlist 6",
        id: 42,
        img: "https://th.bing.com/th/id/OIP.4lfTxOQlytdkKhPZrCvDqgHaHa?w=200&h=200&c=7&r=0&o=5&dpr=1.3&pid=1.7",
        description: "this is the description",
      },
    ],
  },
  {
    category: "throwback",
    title: "Throwback",
    details: [
      {
        name: "Playlist 1",
        id: 43,
        img: "https://th.bing.com/th/id/OIP.YfH0AlZUFDgsK3T0BtcBeAHaHa?w=159&h=180&c=7&r=0&o=5&dpr=1.3&pid=1.7",
        description: "this is the description",
      },
      {
        name: "Playlist 2",
        id: 44,
        img: "https://th.bing.com/th/id/OIP.YfH0AlZUFDgsK3T0BtcBeAHaHa?w=159&h=180&c=7&r=0&o=5&dpr=1.3&pid=1.7",
        description: "this is the description",
      },
      {
        name: "Playlist 3",
        id: 45,
        img: "https://th.bing.com/th/id/OIP.YfH0AlZUFDgsK3T0BtcBeAHaHa?w=159&h=180&c=7&r=0&o=5&dpr=1.3&pid=1.7",
        description: "this is the description",
      },
      {
        name: "Playlist 4",
        id: 46,
        img: "https://th.bing.com/th/id/OIP.YfH0AlZUFDgsK3T0BtcBeAHaHa?w=159&h=180&c=7&r=0&o=5&dpr=1.3&pid=1.7",
        description: "this is the description",
      },
      {
        name: "Playlist 5",
        id: 47,
        img: "https://th.bing.com/th/id/OIP.YfH0AlZUFDgsK3T0BtcBeAHaHa?w=159&h=180&c=7&r=0&o=5&dpr=1.3&pid=1.7",
        description: "this is the description",
      },
      {
        name: "Playlist 6",
        id: 48,
        img: "https://th.bing.com/th/id/OIP.YfH0AlZUFDgsK3T0BtcBeAHaHa?w=159&h=180&c=7&r=0&o=5&dpr=1.3&pid=1.7",
        description: "this is the description",
      },
    ],
  },
  {
    category: "R&B",
    title: "R&B",
    details: [
      {
        name: "Playlist 1",
        id: 49,
        img: "https://th.bing.com/th/id/OIP.MOog_JS9qqEM7nNUz-xZpwHaHV?w=200&h=198&c=7&r=0&o=5&dpr=1.3&pid=1.7",
        description: "this is the description",
      },
      {
        name: "Playlist 2",
        id: 50,
        img: "https://th.bing.com/th/id/OIP.MOog_JS9qqEM7nNUz-xZpwHaHV?w=200&h=198&c=7&r=0&o=5&dpr=1.3&pid=1.7",
        description: "this is the description",
      },
      {
        name: "Playlist 3",
        id: 51,
        img: "https://th.bing.com/th/id/OIP.MOog_JS9qqEM7nNUz-xZpwHaHV?w=200&h=198&c=7&r=0&o=5&dpr=1.3&pid=1.7",
        description: "this is the description",
      },
      {
        name: "Playlist 4",
        id: 52,
        img: "https://th.bing.com/th/id/OIP.MOog_JS9qqEM7nNUz-xZpwHaHV?w=200&h=198&c=7&r=0&o=5&dpr=1.3&pid=1.7",
        description: "this is the description",
      },
      {
        name: "Playlist 5",
        id: 53,
        img: "https://th.bing.com/th/id/OIP.MOog_JS9qqEM7nNUz-xZpwHaHV?w=200&h=198&c=7&r=0&o=5&dpr=1.3&pid=1.7",
        description: "this is the description",
      },
      {
        name: "Playlist 6",
        id: 54,
        img: "https://th.bing.com/th/id/OIP.MOog_JS9qqEM7nNUz-xZpwHaHV?w=200&h=198&c=7&r=0&o=5&dpr=1.3&pid=1.7",
        description: "this is the description",
      },
    ],
  },
  {
    category: "jazz",
    title: "Jazz",
    details: [
      {
        name: "Playlist 1",
        id: 55,
        img: "http://ts1.mm.bing.net/th?id=OIP.4h_9cRQqfXrfiQXOtgB8vwHaHa&pid=15.1",
        description: "this is the description",
      },
      {
        name: "Playlist 2",
        id: 56,
        img: "http://ts1.mm.bing.net/th?id=OIP.4h_9cRQqfXrfiQXOtgB8vwHaHa&pid=15.1",
        description: "this is the description",
      },
      {
        name: "Playlist 3",
        id: 57,
        img: "http://ts1.mm.bing.net/th?id=OIP.4h_9cRQqfXrfiQXOtgB8vwHaHa&pid=15.1",
        description: "this is the description",
      },
      {
        name: "Playlist 4",
        id: 58,
        img: "http://ts1.mm.bing.net/th?id=OIP.4h_9cRQqfXrfiQXOtgB8vwHaHa&pid=15.1",
        description: "this is the description",
      },
      {
        name: "Playlist 5",
        id: 59,
        img: "http://ts1.mm.bing.net/th?id=OIP.4h_9cRQqfXrfiQXOtgB8vwHaHa&pid=15.1",
        description: "this is the description",
      },
      {
        name: "Playlist 6",
        id: 60,
        img: "http://ts1.mm.bing.net/th?id=OIP.4h_9cRQqfXrfiQXOtgB8vwHaHa&pid=15.1",
        description: "this is the description",
      },
    ],
  },
  {
    category: "classical",
    title: "Classical",
    details: [
      {
        name: "Playlist 1",
        id: 61,
        img: "http://ts2.mm.bing.net/th?id=OIP.HBfkP0r-qE9RtYWvNS5AswHaHa&pid=15.1",
        description: "this is the description",
      },
      {
        name: "Playlist 2",
        id: 62,
        img: "http://ts2.mm.bing.net/th?id=OIP.HBfkP0r-qE9RtYWvNS5AswHaHa&pid=15.1",
        description: "this is the description",
      },
      {
        name: "Playlist 3",
        id: 63,
        img: "http://ts2.mm.bing.net/th?id=OIP.HBfkP0r-qE9RtYWvNS5AswHaHa&pid=15.1",
        description: "this is the description",
      },
      {
        name: "Playlist 4",
        id: 64,
        img: "http://ts2.mm.bing.net/th?id=OIP.HBfkP0r-qE9RtYWvNS5AswHaHa&pid=15.1",
        description: "this is the description",
      },
      {
        name: "Playlist 5",
        id: 65,
        img: "http://ts2.mm.bing.net/th?id=OIP.HBfkP0r-qE9RtYWvNS5AswHaHa&pid=15.1",
        description: "this is the description",
      },
      {
        name: "Playlist 6",
        id: 66,
        img: "http://ts2.mm.bing.net/th?id=OIP.HBfkP0r-qE9RtYWvNS5AswHaHa&pid=15.1",
        description: "this is the description",
      },
    ],
  },
  {
    category: "anime",
    title: "Anime",
    details: [
      {
        name: "Playlist 1",
        id: 67,
        img: "https://th.bing.com/th/id/OIP.bLO3d1tTX-_K_wANPMcfxAHaEo?w=253&h=180&c=7&r=0&o=5&dpr=1.3&pid=1.7",
        description: "this is the description",
      },
      {
        name: "Playlist 2",
        id: 68,
        img: "https://th.bing.com/th/id/OIP.bLO3d1tTX-_K_wANPMcfxAHaEo?w=253&h=180&c=7&r=0&o=5&dpr=1.3&pid=1.7",
        description: "this is the description",
      },
      {
        name: "Playlist 3",
        id: 69,
        img: "https://th.bing.com/th/id/OIP.bLO3d1tTX-_K_wANPMcfxAHaEo?w=253&h=180&c=7&r=0&o=5&dpr=1.3&pid=1.7",
        description: "this is the description",
      },
      {
        name: "Playlist 4",
        id: 70,
        img: "https://th.bing.com/th/id/OIP.bLO3d1tTX-_K_wANPMcfxAHaEo?w=253&h=180&c=7&r=0&o=5&dpr=1.3&pid=1.7",
        description: "this is the description",
      },
      {
        name: "Playlist 5",
        id: 71,
        img: "https://th.bing.com/th/id/OIP.bLO3d1tTX-_K_wANPMcfxAHaEo?w=253&h=180&c=7&r=0&o=5&dpr=1.3&pid=1.7",
        description: "this is the description",
      },
      {
        name: "Playlist 6",
        id: 72,
        img: "https://th.bing.com/th/id/OIP.bLO3d1tTX-_K_wANPMcfxAHaEo?w=253&h=180&c=7&r=0&o=5&dpr=1.3&pid=1.7",
        description: "this is the description",
      },
    ],
  },
  {
    category: "workout",
    title: "Workout",
    details: [
      {
        name: "Playlist 1",
        id: 73,
        img: "https://th.bing.com/th/id/OIP.NEGIEdTFP8nCuHbyaEHwWgHaHa?w=183&h=183&c=7&r=0&o=5&dpr=1.3&pid=1.7g",
        description: "this is the description",
      },
      {
        name: "Playlist 2",
        id: 74,
        img: "https://th.bing.com/th/id/OIP.NEGIEdTFP8nCuHbyaEHwWgHaHa?w=183&h=183&c=7&r=0&o=5&dpr=1.3&pid=1.7g",
        description: "this is the description",
      },
      {
        name: "Playlist 3",
        id: 75,
        img: "https://th.bing.com/th/id/OIP.NEGIEdTFP8nCuHbyaEHwWgHaHa?w=183&h=183&c=7&r=0&o=5&dpr=1.3&pid=1.7g",
        description: "this is the description",
      },
      {
        name: "Playlist 4",
        id: 76,
        img: "https://th.bing.com/th/id/OIP.NEGIEdTFP8nCuHbyaEHwWgHaHa?w=183&h=183&c=7&r=0&o=5&dpr=1.3&pid=1.7g",
        description: "this is the description",
      },
      {
        name: "Playlist 5",
        id: 77,
        img: "https://th.bing.com/th/id/OIP.NEGIEdTFP8nCuHbyaEHwWgHaHa?w=183&h=183&c=7&r=0&o=5&dpr=1.3&pid=1.7g",
        description: "this is the description",
      },
      {
        name: "Playlist 6",
        id: 78,
        img: "https://th.bing.com/th/id/OIP.NEGIEdTFP8nCuHbyaEHwWgHaHa?w=183&h=183&c=7&r=0&o=5&dpr=1.3&pid=1.7g",
        description: "this is the description",
      },
    ],
  },
];
