export const playlistCategories = [
  {
    category: "pop",
    title: "Pop",
    details: [
      {
        name: "Top Pop",
        id: 1,
        img: "https://i.scdn.co/image/ab67706f00000003b82f5272ca913b85b73f1690",
        description: "Bringing the pop.",
      },
      {
        name: "Pop Music",
        id: 2,
        img: "https://th.bing.com/th/id/OIP.X6Bv0OhuZCjTWHKbPABwjAHaHa?w=182&h=182&c=7&r=0&o=5&dpr=1.3&pid=1.7",
        description: "Pop hits.",
      },
      {
        name: "Pop",
        id: 3,
        img: "https://th.bing.com/th/id/OIP.2MzWXHRHaX6-sYliciRc1AAAAA?rs=1&pid=ImgDetMain",
        description: "Music, pop style.",
      },
      {
        name: "Now That's What I Call Pop",
        id: 4,
        img: "https://th.bing.com/th/id/OIP.5JL1V9hPFPddTh61XBd1ggHaGr?rs=1&pid=ImgDetMain",
        description: "Greatest pop hits.",
      },
    ],
  },
  {
    category: "rock",
    title: "Rock",
    details: [
      {
        name: "Rock",
        id: 5,
        img: "https://th.bing.com/th/id/OIP.FduqH2omwjTUl38Q6eqICAHaHa?w=192&h=191&c=7&r=0&o=5&dpr=1.3&pid=1.7",
        description: "Rock on.",
      },
      {
        name: "Rock Covers",
        id: 6,
        img: "https://th.bing.com/th/id/OIP.KiLvm9LGrSPFJub-z1-jAQAAAA?rs=1&pid=ImgDetMain",
        description: "Rock covers of the greatest hits.",
      },
      {
        name: "Rock 'n' Roll",
        id: 7,
        img: "https://i.pinimg.com/originals/36/97/ea/3697eaa4bfff0ce5360cee36bf14782c.jpg",
        description: "Keep on rocking!",
      },
      {
        name: "Rock Classics",
        id: 8,
        img: "https://th.bing.com/th/id/OIP.hy70mRt11OcdY8Y7kykDawHaHa?rs=1&pid=ImgDetMain",
        description: "When you need to re-live the classic hits.",
      },
    ],
  },
  {
    category: "hiphop",
    title: "Hip-Hop",
    details: [
      {
        name: "Hip Hop Essentials",
        id: 9,
        img: "https://d1csarkz8obe9u.cloudfront.net/posterpreviews/hip-hop-spotify-playlist-cover-design-template-eb9d61a39fd0772fd8f6774a228a0cf0_screen.jpg?ts=1685333804",
        description: "Essential hip hop hits.",
      },
      {
        name: "Hip Hop Playlist",
        id: 10,
        img: "https://is5-ssl.mzstatic.com/image/thumb/Music112/v4/a0/07/79/a0077928-8da4-9550-433c-5103919c8c6b/5059460145863.jpg/1200x1200bf-60.jpg",
        description: "Hip hop tracks.",
      },
      {
        name: "Chill Hip Hop Beats",
        id: 11,
        img: "https://m.media-amazon.com/images/I/51ikbvRhheL.jpg",
        description: "Chill hip hop songs.",
      },
      {
        name: "Hip Hop Music",
        id: 12,
        img: "https://play-lh.googleusercontent.com/KjS2mK6nB8HsT51ylv-ZF7ny5DoU49qk-ibNKZCbix-MAFOeG_xZvFlhbgdv9iVXqkQ",
        description: "Your daily dose of hip hop.",
      },
    ],
  },
  {
    category: "mood",
    title: "Mood",
    details: [
      {
        name: "Mood Booster",
        id: 13,
        img: "https://th.bing.com/th/id/OIP.yLawNOQYrIk8arwLpUA7twHaHa?rs=1&pid=ImgDetMain",
        description: "Songs to boost the mood.",
      },
      {
        name: "Mood",
        id: 14,
        img: "https://i.scdn.co/image/ab67706f0000000256252858721fbfe408dcf9ed",
        description: "Mood.",
      },
      {
        name: "Afrobeats Mood",
        id: 15,
        img: "https://i1.sndcdn.com/avatars-hfEolOy0Jo4BXgyM-l6Cqgg-t500x500.jpg",
        description: "Afrobeat mood tracks.",
      },
      {
        name: "Chill Ride",
        id: 16,
        img: "https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/f/0ff3b6d2-d6cc-4660-822e-70ced4024755/dfjq5nx-201db2fe-a23e-491f-a88d-02457cb50fc9.gif/v1/fill/w_894,h_894,q_85,strp/chill_ride_by_slastbeast_dfjq5nx-pre.jpg?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOjdlMGQxODg5ODIyNjQzNzNhNWYwZDQxNWVhMGQyNmUwIiwiaXNzIjoidXJuOmFwcDo3ZTBkMTg4OTgyMjY0MzczYTVmMGQ0MTVlYTBkMjZlMCIsIm9iaiI6W1t7ImhlaWdodCI6Ijw9MTA4MCIsInBhdGgiOiJcL2ZcLzBmZjNiNmQyLWQ2Y2MtNDY2MC04MjJlLTcwY2VkNDAyNDc1NVwvZGZqcTVueC0yMDFkYjJmZS1hMjNlLTQ5MWYtYTg4ZC0wMjQ1N2NiNTBmYzkuZ2lmIiwid2lkdGgiOiI8PTEwODAifV1dLCJhdWQiOlsidXJuOnNlcnZpY2U6aW1hZ2Uub3BlcmF0aW9ucyJdfQ.FtIzimobxxZGIBmDh6RpxwJbQxNoRM3EQESRyA_2XpU",
        description: "Mood music for the road.",
      },
    ],
  },
  {
    category: "party",
    title: "Party",
    details: [
      {
        name: "Dance Party",
        id: 17,
        img: "https://i.scdn.co/image/ab67706c0000da84069257f3f45ae78badf609ba",
        description: "Dance party anthems.",
      },
      {
        name: "Top 50 Party Hits",
        id: 18,
        img: "https://m.media-amazon.com/images/I/81RWZ6Rm2cL._SS500_.jpg",
        description: "Classic party hits.",
      },
      {
        name: "Ultimate Disco Anthems",
        id: 19,
        img: "https://m.media-amazon.com/images/I/61Y1mabvseL.jpg",
        description: "The top disco hits.",
      },
      {
        name: "Now That's What I Call Party Anthems",
        id: 20,
        img: "https://images.genius.com/904e4a6d0c7b93a453beb348d5de4a2c.640x640x1.jpg",
        description: "Let's get the party started.",
      },
    ],
  },
  {
    category: "kpop",
    title: "K-Pop",
    details: [
      {
        name: "Playlist 1",
        id: 31,
        img: "https://th.bing.com/th/id/OIP.YvjJgFrFcGMyVd6S2y2tBgHaHa?w=160&h=180&c=7&r=0&o=5&dpr=1.3&pid=1.7",
        description: "this is the description",
      },
      {
        name: "Playlist 2",
        id: 32,
        img: "https://th.bing.com/th/id/OIP.YvjJgFrFcGMyVd6S2y2tBgHaHa?w=160&h=180&c=7&r=0&o=5&dpr=1.3&pid=1.7",
        description: "this is the description",
      },
      {
        name: "Playlist 3",
        id: 33,
        img: "https://th.bing.com/th/id/OIP.YvjJgFrFcGMyVd6S2y2tBgHaHa?w=160&h=180&c=7&r=0&o=5&dpr=1.3&pid=1.7",
        description: "this is the description",
      },
      {
        name: "Playlist 4",
        id: 34,
        img: "https://th.bing.com/th/id/OIP.YvjJgFrFcGMyVd6S2y2tBgHaHa?w=160&h=180&c=7&r=0&o=5&dpr=1.3&pid=1.7",
        description: "this is the description",
      },
      {
        name: "Playlist 5",
        id: 35,
        img: "https://th.bing.com/th/id/OIP.YvjJgFrFcGMyVd6S2y2tBgHaHa?w=160&h=180&c=7&r=0&o=5&dpr=1.3&pid=1.7",
        description: "this is the description",
      },
      {
        name: "Playlist 6",
        id: 36,
        img: "https://th.bing.com/th/id/OIP.YvjJgFrFcGMyVd6S2y2tBgHaHa?w=160&h=180&c=7&r=0&o=5&dpr=1.3&pid=1.7",
        description: "this is the description",
      },
    ],
  },
  {
    category: "indie",
    title: "Indie",
    details: [
      {
        name: "Playlist 1",
        id: 37,
        img: "https://th.bing.com/th/id/OIP.4lfTxOQlytdkKhPZrCvDqgHaHa?w=200&h=200&c=7&r=0&o=5&dpr=1.3&pid=1.7",
        description: "this is the description",
      },
      {
        name: "Playlist 2",
        id: 38,
        img: "https://th.bing.com/th/id/OIP.4lfTxOQlytdkKhPZrCvDqgHaHa?w=200&h=200&c=7&r=0&o=5&dpr=1.3&pid=1.7",
        description: "this is the description",
      },
      {
        name: "Playlist 3",
        id: 39,
        img: "https://th.bing.com/th/id/OIP.4lfTxOQlytdkKhPZrCvDqgHaHa?w=200&h=200&c=7&r=0&o=5&dpr=1.3&pid=1.7",
        description: "this is the description",
      },
      {
        name: "Playlist 4",
        id: 40,
        img: "https://th.bing.com/th/id/OIP.4lfTxOQlytdkKhPZrCvDqgHaHa?w=200&h=200&c=7&r=0&o=5&dpr=1.3&pid=1.7",
        description: "this is the description",
      },
      {
        name: "Playlist 5",
        id: 41,
        img: "https://th.bing.com/th/id/OIP.4lfTxOQlytdkKhPZrCvDqgHaHa?w=200&h=200&c=7&r=0&o=5&dpr=1.3&pid=1.7",
        description: "this is the description",
      },
      {
        name: "Playlist 6",
        id: 42,
        img: "https://th.bing.com/th/id/OIP.4lfTxOQlytdkKhPZrCvDqgHaHa?w=200&h=200&c=7&r=0&o=5&dpr=1.3&pid=1.7",
        description: "this is the description",
      },
    ],
  },
  {
    category: "throwback",
    title: "Throwback",
    details: [
      {
        name: "Playlist 1",
        id: 43,
        img: "https://th.bing.com/th/id/OIP.YfH0AlZUFDgsK3T0BtcBeAHaHa?w=159&h=180&c=7&r=0&o=5&dpr=1.3&pid=1.7",
        description: "this is the description",
      },
      {
        name: "Playlist 2",
        id: 44,
        img: "https://th.bing.com/th/id/OIP.YfH0AlZUFDgsK3T0BtcBeAHaHa?w=159&h=180&c=7&r=0&o=5&dpr=1.3&pid=1.7",
        description: "this is the description",
      },
      {
        name: "Playlist 3",
        id: 45,
        img: "https://th.bing.com/th/id/OIP.YfH0AlZUFDgsK3T0BtcBeAHaHa?w=159&h=180&c=7&r=0&o=5&dpr=1.3&pid=1.7",
        description: "this is the description",
      },
      {
        name: "Playlist 4",
        id: 46,
        img: "https://th.bing.com/th/id/OIP.YfH0AlZUFDgsK3T0BtcBeAHaHa?w=159&h=180&c=7&r=0&o=5&dpr=1.3&pid=1.7",
        description: "this is the description",
      },
      {
        name: "Playlist 5",
        id: 47,
        img: "https://th.bing.com/th/id/OIP.YfH0AlZUFDgsK3T0BtcBeAHaHa?w=159&h=180&c=7&r=0&o=5&dpr=1.3&pid=1.7",
        description: "this is the description",
      },
      {
        name: "Playlist 6",
        id: 48,
        img: "https://th.bing.com/th/id/OIP.YfH0AlZUFDgsK3T0BtcBeAHaHa?w=159&h=180&c=7&r=0&o=5&dpr=1.3&pid=1.7",
        description: "this is the description",
      },
    ],
  },
  {
    category: "R&B",
    title: "R&B",
    details: [
      {
        name: "Playlist 1",
        id: 49,
        img: "https://th.bing.com/th/id/OIP.MOog_JS9qqEM7nNUz-xZpwHaHV?w=200&h=198&c=7&r=0&o=5&dpr=1.3&pid=1.7",
        description: "this is the description",
      },
      {
        name: "Playlist 2",
        id: 50,
        img: "https://th.bing.com/th/id/OIP.MOog_JS9qqEM7nNUz-xZpwHaHV?w=200&h=198&c=7&r=0&o=5&dpr=1.3&pid=1.7",
        description: "this is the description",
      },
      {
        name: "Playlist 3",
        id: 51,
        img: "https://th.bing.com/th/id/OIP.MOog_JS9qqEM7nNUz-xZpwHaHV?w=200&h=198&c=7&r=0&o=5&dpr=1.3&pid=1.7",
        description: "this is the description",
      },
      {
        name: "Playlist 4",
        id: 52,
        img: "https://th.bing.com/th/id/OIP.MOog_JS9qqEM7nNUz-xZpwHaHV?w=200&h=198&c=7&r=0&o=5&dpr=1.3&pid=1.7",
        description: "this is the description",
      },
      {
        name: "Playlist 5",
        id: 53,
        img: "https://th.bing.com/th/id/OIP.MOog_JS9qqEM7nNUz-xZpwHaHV?w=200&h=198&c=7&r=0&o=5&dpr=1.3&pid=1.7",
        description: "this is the description",
      },
      {
        name: "Playlist 6",
        id: 54,
        img: "https://th.bing.com/th/id/OIP.MOog_JS9qqEM7nNUz-xZpwHaHV?w=200&h=198&c=7&r=0&o=5&dpr=1.3&pid=1.7",
        description: "this is the description",
      },
    ],
  },
  {
    category: "jazz",
    title: "Jazz",
    details: [
      {
        name: "Playlist 1",
        id: 55,
        img: "http://ts1.mm.bing.net/th?id=OIP.4h_9cRQqfXrfiQXOtgB8vwHaHa&pid=15.1",
        description: "this is the description",
      },
      {
        name: "Playlist 2",
        id: 56,
        img: "http://ts1.mm.bing.net/th?id=OIP.4h_9cRQqfXrfiQXOtgB8vwHaHa&pid=15.1",
        description: "this is the description",
      },
      {
        name: "Playlist 3",
        id: 57,
        img: "http://ts1.mm.bing.net/th?id=OIP.4h_9cRQqfXrfiQXOtgB8vwHaHa&pid=15.1",
        description: "this is the description",
      },
      {
        name: "Playlist 4",
        id: 58,
        img: "http://ts1.mm.bing.net/th?id=OIP.4h_9cRQqfXrfiQXOtgB8vwHaHa&pid=15.1",
        description: "this is the description",
      },
      {
        name: "Playlist 5",
        id: 59,
        img: "http://ts1.mm.bing.net/th?id=OIP.4h_9cRQqfXrfiQXOtgB8vwHaHa&pid=15.1",
        description: "this is the description",
      },
      {
        name: "Playlist 6",
        id: 60,
        img: "http://ts1.mm.bing.net/th?id=OIP.4h_9cRQqfXrfiQXOtgB8vwHaHa&pid=15.1",
        description: "this is the description",
      },
    ],
  },
  {
    category: "classical",
    title: "Classical",
    details: [
      {
        name: "Playlist 1",
        id: 61,
        img: "http://ts2.mm.bing.net/th?id=OIP.HBfkP0r-qE9RtYWvNS5AswHaHa&pid=15.1",
        description: "this is the description",
      },
      {
        name: "Playlist 2",
        id: 62,
        img: "http://ts2.mm.bing.net/th?id=OIP.HBfkP0r-qE9RtYWvNS5AswHaHa&pid=15.1",
        description: "this is the description",
      },
      {
        name: "Playlist 3",
        id: 63,
        img: "http://ts2.mm.bing.net/th?id=OIP.HBfkP0r-qE9RtYWvNS5AswHaHa&pid=15.1",
        description: "this is the description",
      },
      {
        name: "Playlist 4",
        id: 64,
        img: "http://ts2.mm.bing.net/th?id=OIP.HBfkP0r-qE9RtYWvNS5AswHaHa&pid=15.1",
        description: "this is the description",
      },
      {
        name: "Playlist 5",
        id: 65,
        img: "http://ts2.mm.bing.net/th?id=OIP.HBfkP0r-qE9RtYWvNS5AswHaHa&pid=15.1",
        description: "this is the description",
      },
      {
        name: "Playlist 6",
        id: 66,
        img: "http://ts2.mm.bing.net/th?id=OIP.HBfkP0r-qE9RtYWvNS5AswHaHa&pid=15.1",
        description: "this is the description",
      },
    ],
  },
  {
    category: "anime",
    title: "Anime",
    details: [
      {
        name: "Playlist 1",
        id: 67,
        img: "https://th.bing.com/th/id/OIP.bLO3d1tTX-_K_wANPMcfxAHaEo?w=253&h=180&c=7&r=0&o=5&dpr=1.3&pid=1.7",
        description: "this is the description",
      },
      {
        name: "Playlist 2",
        id: 68,
        img: "https://th.bing.com/th/id/OIP.bLO3d1tTX-_K_wANPMcfxAHaEo?w=253&h=180&c=7&r=0&o=5&dpr=1.3&pid=1.7",
        description: "this is the description",
      },
      {
        name: "Playlist 3",
        id: 69,
        img: "https://th.bing.com/th/id/OIP.bLO3d1tTX-_K_wANPMcfxAHaEo?w=253&h=180&c=7&r=0&o=5&dpr=1.3&pid=1.7",
        description: "this is the description",
      },
      {
        name: "Playlist 4",
        id: 70,
        img: "https://th.bing.com/th/id/OIP.bLO3d1tTX-_K_wANPMcfxAHaEo?w=253&h=180&c=7&r=0&o=5&dpr=1.3&pid=1.7",
        description: "this is the description",
      },
      {
        name: "Playlist 5",
        id: 71,
        img: "https://th.bing.com/th/id/OIP.bLO3d1tTX-_K_wANPMcfxAHaEo?w=253&h=180&c=7&r=0&o=5&dpr=1.3&pid=1.7",
        description: "this is the description",
      },
      {
        name: "Playlist 6",
        id: 72,
        img: "https://th.bing.com/th/id/OIP.bLO3d1tTX-_K_wANPMcfxAHaEo?w=253&h=180&c=7&r=0&o=5&dpr=1.3&pid=1.7",
        description: "this is the description",
      },
    ],
  },
  {
    category: "workout",
    title: "Workout",
    details: [
      {
        name: "Playlist 1",
        id: 73,
        img: "https://th.bing.com/th/id/OIP.NEGIEdTFP8nCuHbyaEHwWgHaHa?w=183&h=183&c=7&r=0&o=5&dpr=1.3&pid=1.7g",
        description: "this is the description",
      },
      {
        name: "Playlist 2",
        id: 74,
        img: "https://th.bing.com/th/id/OIP.NEGIEdTFP8nCuHbyaEHwWgHaHa?w=183&h=183&c=7&r=0&o=5&dpr=1.3&pid=1.7g",
        description: "this is the description",
      },
      {
        name: "Playlist 3",
        id: 75,
        img: "https://th.bing.com/th/id/OIP.NEGIEdTFP8nCuHbyaEHwWgHaHa?w=183&h=183&c=7&r=0&o=5&dpr=1.3&pid=1.7g",
        description: "this is the description",
      },
      {
        name: "Playlist 4",
        id: 76,
        img: "https://th.bing.com/th/id/OIP.NEGIEdTFP8nCuHbyaEHwWgHaHa?w=183&h=183&c=7&r=0&o=5&dpr=1.3&pid=1.7g",
        description: "this is the description",
      },
      {
        name: "Playlist 5",
        id: 77,
        img: "https://th.bing.com/th/id/OIP.NEGIEdTFP8nCuHbyaEHwWgHaHa?w=183&h=183&c=7&r=0&o=5&dpr=1.3&pid=1.7g",
        description: "this is the description",
      },
      {
        name: "Playlist 6",
        id: 78,
        img: "https://th.bing.com/th/id/OIP.NEGIEdTFP8nCuHbyaEHwWgHaHa?w=183&h=183&c=7&r=0&o=5&dpr=1.3&pid=1.7g",
        description: "this is the description",
      },
    ],
  },
];
