export const playlistCategories = [
  {
    category: "pop",
    title: "Pop",
    details: [
      {
        name: "Today's Top Hits",
        id: 1,
        img: "https://i.scdn.co/image/ab67706f00000002560577e34d449bc5dd1a3ac2",
        description: "The hottest 50. Cover: Lola Young",
      },
      {
        name: "Pop Rising",
        id: 2,
        img: "https://i.scdn.co/image/ab67706f00000002e5db5b29bc24cdbcfda5c85b",
        description: "Who's now and next in pop. Cover: JADE",
      },
      {
        name: "Global Video Hits",
        id: 3,
        img: "https://i.scdn.co/image/ab67706f00000002594c9a2fdfe6f552dc5ffdd4",
        description: "Watch hit songs from around the world now!",
      },
      {
        name: "Pop Sauce",
        id: 4,
        img: "https://i.scdn.co/image/ab67706f00000002f4e79179ba48e063d273741c",
        description: "Next gen pop. Cover: Rose Gray",
      },
    ],
  },
  {
    category: "rock",
    title: "Rock",
    details: [
      {
        name: "All New Rock",
        id: 5,
        img: "https://i.scdn.co/image/ab67706f00000002850dddfe198bc8bf3eecf7d9",
        description: "The best new rock and alternative tracks.",
      },
      {
        name: "Rock Party",
        id: 6,
        img: "https://i.scdn.co/image/ab67706f000000029bbc38dae393e154d84dae40",
        description: "The ultimate rock party playlist.",
      },
      {
        name: "Rock Ballads",
        id: 7,
        img: "https://i.scdn.co/image/ab67706f00000002b20ba957151535f9d877c9c0",
        description: "Lighters up.",
      },
      {
        name: "Screaming",
        id: 8,
        img: "https://i.scdn.co/image/ab67706f00000002b96be7e1a6cf3ded583a6e8f",
        description: "Ahhhhhhhhhhhhhh",
      },
    ],
  },
  {
    category: "hiphop",
    title: "Hip-Hop",
    details: [
      {
        name: "Gold School",
        id: 9,
        img: "https://i.scdn.co/image/ab67706f000000027e7eaf76d41b1ee0c0f37f44",
        description: "Taking it way back. Cover: The Game",
      },
      {
        name: "Global Hip-Hop",
        id: 10,
        img: "https://i.scdn.co/image/ab67706f000000024d6161ecc9566f180f5c8396",
        description: "Hip-hop from around the world.",
      },
      {
        name: "West Coast Classics",
        id: 11,
        img: "https://i.scdn.co/image/ab67706f000000024e90ffb7c06ef259b2933ebc",
        description: "The best side. Cover: Dr. Dre",
      },
      {
        name: "2000s Hip-Hop",
        id: 12,
        img: "https://i.scdn.co/image/ab67706f00000002857d926d3c997a622a6f8fdf",
        description: "Taking it back to the 2000s. Cover: Cam'ron",
      },
    ],
  },
  {
    category: "mood",
    title: "Mood",
    details: [
      {
        name: "Mood Booster",
        id: 13,
        img: "https://th.bing.com/th/id/OIP.yLawNOQYrIk8arwLpUA7twHaHa?rs=1&pid=ImgDetMain",
        description: "Songs to boost the mood.",
      },
      {
        name: "Wake Up Happy",
        id: 14,
        img: "https://i.scdn.co/image/ab67706f000000026b30471dcc036d254dcc8041",
        description: "Set the mood with these happy songs.",
      },
      {
        name: "Deep Focus",
        id: 15,
        img: "https://i.scdn.co/image/ab67706f00000002f3ce4c5b615e345331a22830",
        description: "Keep calm and focused with these tracks.",
      },
      {
        name: "Lofi Sleep",
        id: 16,
        img: "https://i.scdn.co/image/ab67706f00000002325a73f69fa4fef821080f25",
        description: "Instrumental beats for a restful night's sleep.",
      },
    ],
  },
  {
    category: "party",
    title: "Party",
    details: [
      {
        name: "Party Hits 2010s",
        id: 17,
        img: "https://i.scdn.co/image/ab67706f00000002585387ab929e2dbc6465b528",
        description: "The biggest party hits of the 2010s.",
      },
      {
        name: "Dance Party",
        id: 18,
        img: "https://i.scdn.co/image/ab67706f00000002d2c23cff8e4056e5c891216d",
        description: "Dance to the rhythm and move your.",
      },
      {
        name: "Dance Hits",
        id: 19,
        img: "https://i.scdn.co/image/ab67706f0000000240b711f0986fdd846867c4ee",
        description: "All the big ones.",
      },
      {
        name: "Pop Party",
        id: 20,
        img: "https://i.scdn.co/image/ab67706f00000002dce5bc8321d570243742d421",
        description: "A perfect little pop party.",
      },
    ],
  },
  {
    category: "kpop",
    title: "K-Pop",
    details: [
      {
        name: "K-Pop ON!",
        id: 21,
        img: "https://th.bing.com/th/id/OIP.D8Lv2zXw4nXzWKV7HahnVwHaHa?rs=1&pid=ImgDetMain",
        description: "K-Pop on top.",
      },
      {
        name: "KimBops!",
        id: 22,
        img: "https://i.scdn.co/image/ab67706f000000024e2bba1985bab0e266e6f5c8",
        description: "Rolling with the 'bops' in your Kimbap.",
      },
      {
        name: "K-Pop Rising",
        id: 23,
        img: "https://i.scdn.co/image/ab67706f000000029848efabec0234fec73f6102",
        description: "Future K-Pop hits! Cover: ONEUS",
      },
      {
        name: "New Music K-Pop",
        id: 24,
        img: "https://i.scdn.co/image/ab67706f00000002d0293f854c0e9ae4fe1c55f2",
        description: "Enjoy the freshest K-Pop new releases.",
      },
    ],
  },
  {
    category: "indie",
    title: "Indie",
    details: [
      {
        name: "Playlist 1",
        id: 37,
        img: "https://th.bing.com/th/id/OIP.4lfTxOQlytdkKhPZrCvDqgHaHa?w=200&h=200&c=7&r=0&o=5&dpr=1.3&pid=1.7",
        description: "this is the description",
      },
      {
        name: "Playlist 2",
        id: 38,
        img: "https://th.bing.com/th/id/OIP.4lfTxOQlytdkKhPZrCvDqgHaHa?w=200&h=200&c=7&r=0&o=5&dpr=1.3&pid=1.7",
        description: "this is the description",
      },
      {
        name: "Playlist 3",
        id: 39,
        img: "https://th.bing.com/th/id/OIP.4lfTxOQlytdkKhPZrCvDqgHaHa?w=200&h=200&c=7&r=0&o=5&dpr=1.3&pid=1.7",
        description: "this is the description",
      },
      {
        name: "Playlist 4",
        id: 40,
        img: "https://th.bing.com/th/id/OIP.4lfTxOQlytdkKhPZrCvDqgHaHa?w=200&h=200&c=7&r=0&o=5&dpr=1.3&pid=1.7",
        description: "this is the description",
      },
      {
        name: "Playlist 5",
        id: 41,
        img: "https://th.bing.com/th/id/OIP.4lfTxOQlytdkKhPZrCvDqgHaHa?w=200&h=200&c=7&r=0&o=5&dpr=1.3&pid=1.7",
        description: "this is the description",
      },
      {
        name: "Playlist 6",
        id: 42,
        img: "https://th.bing.com/th/id/OIP.4lfTxOQlytdkKhPZrCvDqgHaHa?w=200&h=200&c=7&r=0&o=5&dpr=1.3&pid=1.7",
        description: "this is the description",
      },
    ],
  },
  {
    category: "throwback",
    title: "Throwback",
    details: [
      {
        name: "Playlist 1",
        id: 43,
        img: "https://th.bing.com/th/id/OIP.YfH0AlZUFDgsK3T0BtcBeAHaHa?w=159&h=180&c=7&r=0&o=5&dpr=1.3&pid=1.7",
        description: "this is the description",
      },
      {
        name: "Playlist 2",
        id: 44,
        img: "https://th.bing.com/th/id/OIP.YfH0AlZUFDgsK3T0BtcBeAHaHa?w=159&h=180&c=7&r=0&o=5&dpr=1.3&pid=1.7",
        description: "this is the description",
      },
      {
        name: "Playlist 3",
        id: 45,
        img: "https://th.bing.com/th/id/OIP.YfH0AlZUFDgsK3T0BtcBeAHaHa?w=159&h=180&c=7&r=0&o=5&dpr=1.3&pid=1.7",
        description: "this is the description",
      },
      {
        name: "Playlist 4",
        id: 46,
        img: "https://th.bing.com/th/id/OIP.YfH0AlZUFDgsK3T0BtcBeAHaHa?w=159&h=180&c=7&r=0&o=5&dpr=1.3&pid=1.7",
        description: "this is the description",
      },
      {
        name: "Playlist 5",
        id: 47,
        img: "https://th.bing.com/th/id/OIP.YfH0AlZUFDgsK3T0BtcBeAHaHa?w=159&h=180&c=7&r=0&o=5&dpr=1.3&pid=1.7",
        description: "this is the description",
      },
      {
        name: "Playlist 6",
        id: 48,
        img: "https://th.bing.com/th/id/OIP.YfH0AlZUFDgsK3T0BtcBeAHaHa?w=159&h=180&c=7&r=0&o=5&dpr=1.3&pid=1.7",
        description: "this is the description",
      },
    ],
  },
  {
    category: "R&B",
    title: "R&B",
    details: [
      {
        name: "Playlist 1",
        id: 49,
        img: "https://th.bing.com/th/id/OIP.MOog_JS9qqEM7nNUz-xZpwHaHV?w=200&h=198&c=7&r=0&o=5&dpr=1.3&pid=1.7",
        description: "this is the description",
      },
      {
        name: "Playlist 2",
        id: 50,
        img: "https://th.bing.com/th/id/OIP.MOog_JS9qqEM7nNUz-xZpwHaHV?w=200&h=198&c=7&r=0&o=5&dpr=1.3&pid=1.7",
        description: "this is the description",
      },
      {
        name: "Playlist 3",
        id: 51,
        img: "https://th.bing.com/th/id/OIP.MOog_JS9qqEM7nNUz-xZpwHaHV?w=200&h=198&c=7&r=0&o=5&dpr=1.3&pid=1.7",
        description: "this is the description",
      },
      {
        name: "Playlist 4",
        id: 52,
        img: "https://th.bing.com/th/id/OIP.MOog_JS9qqEM7nNUz-xZpwHaHV?w=200&h=198&c=7&r=0&o=5&dpr=1.3&pid=1.7",
        description: "this is the description",
      },
      {
        name: "Playlist 5",
        id: 53,
        img: "https://th.bing.com/th/id/OIP.MOog_JS9qqEM7nNUz-xZpwHaHV?w=200&h=198&c=7&r=0&o=5&dpr=1.3&pid=1.7",
        description: "this is the description",
      },
      {
        name: "Playlist 6",
        id: 54,
        img: "https://th.bing.com/th/id/OIP.MOog_JS9qqEM7nNUz-xZpwHaHV?w=200&h=198&c=7&r=0&o=5&dpr=1.3&pid=1.7",
        description: "this is the description",
      },
    ],
  },
  {
    category: "jazz",
    title: "Jazz",
    details: [
      {
        name: "Playlist 1",
        id: 55,
        img: "http://ts1.mm.bing.net/th?id=OIP.4h_9cRQqfXrfiQXOtgB8vwHaHa&pid=15.1",
        description: "this is the description",
      },
      {
        name: "Playlist 2",
        id: 56,
        img: "http://ts1.mm.bing.net/th?id=OIP.4h_9cRQqfXrfiQXOtgB8vwHaHa&pid=15.1",
        description: "this is the description",
      },
      {
        name: "Playlist 3",
        id: 57,
        img: "http://ts1.mm.bing.net/th?id=OIP.4h_9cRQqfXrfiQXOtgB8vwHaHa&pid=15.1",
        description: "this is the description",
      },
      {
        name: "Playlist 4",
        id: 58,
        img: "http://ts1.mm.bing.net/th?id=OIP.4h_9cRQqfXrfiQXOtgB8vwHaHa&pid=15.1",
        description: "this is the description",
      },
      {
        name: "Playlist 5",
        id: 59,
        img: "http://ts1.mm.bing.net/th?id=OIP.4h_9cRQqfXrfiQXOtgB8vwHaHa&pid=15.1",
        description: "this is the description",
      },
      {
        name: "Playlist 6",
        id: 60,
        img: "http://ts1.mm.bing.net/th?id=OIP.4h_9cRQqfXrfiQXOtgB8vwHaHa&pid=15.1",
        description: "this is the description",
      },
    ],
  },
  {
    category: "classical",
    title: "Classical",
    details: [
      {
        name: "Playlist 1",
        id: 61,
        img: "http://ts2.mm.bing.net/th?id=OIP.HBfkP0r-qE9RtYWvNS5AswHaHa&pid=15.1",
        description: "this is the description",
      },
      {
        name: "Playlist 2",
        id: 62,
        img: "http://ts2.mm.bing.net/th?id=OIP.HBfkP0r-qE9RtYWvNS5AswHaHa&pid=15.1",
        description: "this is the description",
      },
      {
        name: "Playlist 3",
        id: 63,
        img: "http://ts2.mm.bing.net/th?id=OIP.HBfkP0r-qE9RtYWvNS5AswHaHa&pid=15.1",
        description: "this is the description",
      },
      {
        name: "Playlist 4",
        id: 64,
        img: "http://ts2.mm.bing.net/th?id=OIP.HBfkP0r-qE9RtYWvNS5AswHaHa&pid=15.1",
        description: "this is the description",
      },
      {
        name: "Playlist 5",
        id: 65,
        img: "http://ts2.mm.bing.net/th?id=OIP.HBfkP0r-qE9RtYWvNS5AswHaHa&pid=15.1",
        description: "this is the description",
      },
      {
        name: "Playlist 6",
        id: 66,
        img: "http://ts2.mm.bing.net/th?id=OIP.HBfkP0r-qE9RtYWvNS5AswHaHa&pid=15.1",
        description: "this is the description",
      },
    ],
  },
  {
    category: "anime",
    title: "Anime",
    details: [
      {
        name: "Playlist 1",
        id: 67,
        img: "https://th.bing.com/th/id/OIP.bLO3d1tTX-_K_wANPMcfxAHaEo?w=253&h=180&c=7&r=0&o=5&dpr=1.3&pid=1.7",
        description: "this is the description",
      },
      {
        name: "Playlist 2",
        id: 68,
        img: "https://th.bing.com/th/id/OIP.bLO3d1tTX-_K_wANPMcfxAHaEo?w=253&h=180&c=7&r=0&o=5&dpr=1.3&pid=1.7",
        description: "this is the description",
      },
      {
        name: "Playlist 3",
        id: 69,
        img: "https://th.bing.com/th/id/OIP.bLO3d1tTX-_K_wANPMcfxAHaEo?w=253&h=180&c=7&r=0&o=5&dpr=1.3&pid=1.7",
        description: "this is the description",
      },
      {
        name: "Playlist 4",
        id: 70,
        img: "https://th.bing.com/th/id/OIP.bLO3d1tTX-_K_wANPMcfxAHaEo?w=253&h=180&c=7&r=0&o=5&dpr=1.3&pid=1.7",
        description: "this is the description",
      },
      {
        name: "Playlist 5",
        id: 71,
        img: "https://th.bing.com/th/id/OIP.bLO3d1tTX-_K_wANPMcfxAHaEo?w=253&h=180&c=7&r=0&o=5&dpr=1.3&pid=1.7",
        description: "this is the description",
      },
      {
        name: "Playlist 6",
        id: 72,
        img: "https://th.bing.com/th/id/OIP.bLO3d1tTX-_K_wANPMcfxAHaEo?w=253&h=180&c=7&r=0&o=5&dpr=1.3&pid=1.7",
        description: "this is the description",
      },
    ],
  },
  {
    category: "workout",
    title: "Workout",
    details: [
      {
        name: "Playlist 1",
        id: 73,
        img: "https://th.bing.com/th/id/OIP.NEGIEdTFP8nCuHbyaEHwWgHaHa?w=183&h=183&c=7&r=0&o=5&dpr=1.3&pid=1.7g",
        description: "this is the description",
      },
      {
        name: "Playlist 2",
        id: 74,
        img: "https://th.bing.com/th/id/OIP.NEGIEdTFP8nCuHbyaEHwWgHaHa?w=183&h=183&c=7&r=0&o=5&dpr=1.3&pid=1.7g",
        description: "this is the description",
      },
      {
        name: "Playlist 3",
        id: 75,
        img: "https://th.bing.com/th/id/OIP.NEGIEdTFP8nCuHbyaEHwWgHaHa?w=183&h=183&c=7&r=0&o=5&dpr=1.3&pid=1.7g",
        description: "this is the description",
      },
      {
        name: "Playlist 4",
        id: 76,
        img: "https://th.bing.com/th/id/OIP.NEGIEdTFP8nCuHbyaEHwWgHaHa?w=183&h=183&c=7&r=0&o=5&dpr=1.3&pid=1.7g",
        description: "this is the description",
      },
      {
        name: "Playlist 5",
        id: 77,
        img: "https://th.bing.com/th/id/OIP.NEGIEdTFP8nCuHbyaEHwWgHaHa?w=183&h=183&c=7&r=0&o=5&dpr=1.3&pid=1.7g",
        description: "this is the description",
      },
      {
        name: "Playlist 6",
        id: 78,
        img: "https://th.bing.com/th/id/OIP.NEGIEdTFP8nCuHbyaEHwWgHaHa?w=183&h=183&c=7&r=0&o=5&dpr=1.3&pid=1.7g",
        description: "this is the description",
      },
    ],
  },
];
